### ISSUE TITLE
discord link?

### ISSUE THREAD

**Issue by mandar1jn** [NefariousTechSupport/igArchiveExtractor#1]
Hello. In the README file, you mention a reverse engineering discord. Could you link me to that?

**Comment by NefariousTechSupport** [comment]
It's invite only, if you reply with your discord i'll send you the link

**Comment by ghost** [comment]
Mandar1jn#0990 DM’s should be open

**Comment by ghost** [comment]
Note: same account as mandar1jn. This is my school account. For proof: both accounts have a repository called planet clash. One is in C (the OG) and the other is typescript (port for school)

**Comment by deReeperJosh** [comment]
Any chance I can also an invite for this? Grim_de#3727
