### ISSUE TITLE
Skylanders Spyro's Adventure (PC)

### ISSUE THREAD

**Issue by kamuixmod** [NefariousTechSupport/igArchiveExtractor#3]
Got my hands on the pc version of Skylanders Spyro's adventure and am trying to get a hold of the music files. Would this perhaps also work with that?

**Comment by NefariousTechSupport** [comment]
Hi! Skylanders Spyro's Adventure (PS3/Xbox 360/PC/Mac) uses the Lux engine as opposed to the Alchemy Engine, as a result, this tool doesn't and isn't intended to support for it.
The Wii and WiiU Versions of the game do use alchemy and will work with it.

However, audio extraction for the Lux engine has been figured out, use a tool called [Ravioli Game Tools](https://www.scampers.org/steve/sms/other.htm) and open the streaming.pck file in it.

**Comment by kamuixmod** [comment]
Hi, i got a hold of the Wii version instead and used it in conjunction with your tool, opening .arc files but it seems to fail extracting the audio files saying : "failed due to unsupported compression..."
