### ISSUE TITLE
Audio Extraction failed "failed due to unsupported compression..."

### ISSUE THREAD

**Issue by kamuixmod** [NefariousTechSupport/igArchiveExtractor#4]
Hi, i got a hold of the Wii version of Skylanders Spyro's Adventure and used it in conjunction with your tool, opening .arc files but it seems to fail extracting the audio files saying : "failed due to unsupported compression..."

The files seem to be in the .wav.hz.wav.enc format

**Comment by NefariousTechSupport** [comment]
Yeah on ssa wii, the audio is stored in the FSB4 format with Nintendo's own DSP encoding (also called GCADPCM)
I used a tool called [fsbext](http://aluigi.altervista.org/search.php?src=fsbext) to extract this into a format called genh, I then used [vgmstream](https://github.com/vgmstream/vgmstream) (download the test.zip file from the releases tab) to convert this into something usable

Yes, it's a process, but hey that's video game modding for ya

**Comment by kamuixmod** [comment]
Ah thank you so much, i was starting to loose my mind. I've been tirelessly trying to get a hold of the Audio Sequences which are used for the final Kaos Battle in Skylanders Spyro's Adventure. 

I still have a slight issue though, dunno if you can help me with that. I've found all of the audio used for each Phase during the battle but 1 which is quite important for me.

https://www.youtube.com/watch?v=TbL_3dp0k_8  (The Audio i'm looking for is represented in the first 6 seconds of this)

The first phase i found however sounds more like this however:

https://www.youtube.com/watch?v=bkSukTqG6z0
