### ISSUE TITLE
Skylanders Giants - Playing audio errors out with "File is corrupt."

### ISSUE THREAD

**Issue by EpicLPer** [NefariousTechSupport/igArchiveExtractor#6]
Heya,

I'm trying to extract some audio files from "Skylanders Giants" for the PS3, so far everything worked really well and I was able to extract the whole dumped disc :) However I'm left with some `.wav.hz.wav.enc` files now which do open in Audacity, but a few samples at the beginning of the file are missing and it sounds a bit distorted.

So I tried opening them directly in igArchiveExtractor, however when I try I get the following error:
![image](https://github.com/NefariousTechSupport/igArchiveExtractor/assets/8442196/d7501c55-caf9-467e-b9d4-01fc6ea015c6)

Is this a bug of the application or something on my end?

Thanks!

**Comment by NefariousTechSupport** [comment]
igArchiveExtractor does not support opening audio files, it says the file is corrupt cos it's expecting the file to be an igz file.

Instead use something like aezey's fsb extractor http://aezay.dk/aezay/fsbextractor/

**Comment by EpicLPer** [comment]
Oh, thanks for the very quick reply :D 

Yes! That worked now :) Thanks a ton!
